services:
  db:
    image: postgres
    environment:
      POSTGRES_USER: task_management_user
      POSTGRES_PASSWORD: task_management_password
      POSTGRES_DB: task_management_app
    ports:
      - 5433:5432
    restart: always
    volumes:
      - ./db:/docker-entrypoint-initdb.d